### PR TITLE
Align look of the dashboard in M breakpoint with L - Closes #1573

### LINKED ISSUE #1573: Align look of the dashboard in M breakpoint with L
Subtask of #1467

Goals:
- Align look of the dashboard in M breakpoint with L
https://taikonauten.invisionapp.com/d/main/#/console/15987783/336075026/preview
screen shot 2018-12-13 at 11 08 21

### PR DESCRIPTION
**Pull request by osvaldovega**
### What issue have I solved?

-- #1573 

### How have I implemented/fixed it?
Based on the new Dashboard design, there is no more scroll on the dashboard components and what we have now is a **Show More** button what increase the size of the component show all the information.

This apply for the **Latest Activity**, **News/Feeds** and **Bookmarks**.

This should looks different when user resize the screen, the arrange of the components is different as before.

### How has this been tested?
In progress

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by osvaldovega** [comment]
@slaweet all changes are done, please check it again and let me know if now is better.

**Comment by slaweet** [comment]
- [ ] The margins of the header are also a problem in M breakpoint
screen shot 2019-01-15 at 11 31 22

- [ ] Let's enable the box shadows in M breakpoint (should be fine if it affects other pages), just remove these two lines
https://github.com/LiskHQ/lisk-hub/blob/ab4a01e4084571b38d3390841e551deaffb17e75/src/components/box/box.css#L56-L57

- [ ] The header has also issues on smaller size of L breakpoint
screen shot 2019-01-15 at 11 36 50

**Comment by osvaldovega** [comment]
@slaweet I just update the css files that fix all these issues

**Comment by slaweet** [comment]
- FIx alignment of header with logo
- Bookmarks module height should keep the same in all XL and L breakpoint
- margin bottom of other pages main box should be smaller

**Comment by osvaldovega** [comment]
@slaweet done, please check again

**Pull request merged**
