### PR TITLE
Show recent searches in autosuggest - Closes #895

### LINKED ISSUE #895: Add "recent searches" to search autosuggest
### Expected behaviour
- Implement new design of recent searches in autosuggest
### Actual behaviour
- Not implemented
### Steps to reproduce

https://taikonauten.atlassian.net/browse/L20-459

### PR DESCRIPTION
**Pull request by faival**
### What was the problem?
- See #895 
### How did I fix it?
- Render search results based on last searches, reuse resultsList module
### How to test it?
- go to explorer or perform some valid searches with the autosuggest. 
- then focus on autosuggest but don't write any value.
### Review checklist
- The PR solves #895 
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by faival** [comment]
placeholder removal will be fixed once #900 merged to 0.10.0 and rebased.

**Comment by slaweet** [comment]
The recent searches could also work with arrow down/up, but it would have the first item selected only after pressing arrow down for the first time.

But I wouldn't implement it now, we can have a follow-up after we have some feedback on how the features is actually used.

**Comment by faival** [comment]
- provide keyboard navigation to recent searches, only fill placeholder on first arrowDown ✅

**Comment by slaweet** [comment]
screen shot 2018-06-18 at 10 29 29
In the initial state:
- it should IMO not highlight the first item, only after the first arrow-down press.
- enter should not do anything if the input field is empty

**Pull request merged**
