### PR TITLE
Double click on "Yes it's safe" breaks whole app - Closes #642

### LINKED ISSUE #642: Double click on "Yes it's safe" breaks whole app
### Expected behaviour
The second click shouldn't preform any actions

### Actual behaviour
As title suggests if we double click on _Yes it's safe_ button in Registration process, the component throws error.

### Steps to reproduce
* Navigate to Register page
* Proceed until you get the passphrase and see the button titled : Yes it's safe.
* double click on it

### PR DESCRIPTION
**Pull request by yasharAyari**
### What was the problem?
As title suggests if we double clicked Yes it's safe button in Registration process, the component throwed error.

### How did I fix it?
Disable the button after first click.

### Review checklist
- The PR solves #642
- All new code is covered with unit tests
- All new features are covered with e2e tests
- All new code follows best practices

### CODE REVIEW

**Comment by alepop** [comment]
@yasharAyari hello! I think, there are a lot of place in the app, then you need to prevent double click, maybe better is to make a HOC component for click elements?

**Comment by reyraa** [comment]
@alepop Correct. thanks for your suggestion. we can create an HOC for all buttons presenting double click event. I'll create a ticket to fix it with next release.

**Comment by yasharAyari** [comment]
@alepop I don't agree with you . I think we can handle all of them with 'disabled' property in button component like this one.

**Comment by alepop** [comment]
@yasharAyari you can create a HOC that will set the `disabled` attribute automatically on the first click. In my opinion, it is better than add all this code in each component.

**Pull request merged**
