### PR TITLE
Code splitting by route - Closes #519

### LINKED ISSUE #519: Code-splitting by routes
### Expected behaviour
Modify `webpack` config and `react routing` code to allow split finish bundle into the chanks by routes. Webpack will generate separate bundles for each of the route.  And app will lazy loading needed modules by visited route. Example: If we visit transactions tab we don't need to load explorer relative modules and etc.

This will improve load performance, especially for mobile devices. 
This issue relative to #509 

### Actual behaviour
Lisk Hub shipped to a user as a single code bundle.

### Steps to reproduce
Visit Lisk Hub.

### PR DESCRIPTION
**Pull request by alepop**
### What was the problem?
We have a big Lisk Hub js bundle that load all components for different routes

### How did I fix it?
Created `asyncComponent` that allows import component only then it needed.
### How to test it?
- Open network tab in dev inspector
- Click different routes and see that code chunks is loaded

Before code splitting:
screen shot 2018-04-04 at 17 00 09

After:
screen shot 2018-04-04 at 16 56 38

### Review checklist
- The PR solves #519 
- All new code follows best practices

### CODE REVIEW

**Comment by slaweet** [comment]
Initial load page size reduced from 4.4 MB [0] to 3.4 MB [1], that's a good chunk of data 👍 . 

Just some unit tests need to be updated.

[0] https://tools.pingdom.com/#!/c1Tls4/https://jenkins.lisk.io/test/lisk-hub/development/
[1] https://tools.pingdom.com/#!/dEpHmc/https://jenkins.lisk.io/test/lisk-hub/PR-678/

**Comment by alepop** [comment]
@slaweet rebased

**Comment by alepop** [comment]
@slaweet is this still relevant if Lisk Hub now will be only shipped as a desktop app?

**Comment by slaweet** [comment]
@alepop IMO it's not relevant anymore. I'll close it now. We can always reopen the pr if the situation changes.

**Pull request closed without merging**
