### PR TITLE
An error occurs on the BTC wallet page - closes #2254

### LINKED ISSUE #2254: An error occurs on the BTC wallet page
### Steps to reproduce

1. Select Bitcoin Wallet
btc_select

2. Select Wallet
wallet_select

**Error log:**
> balanceChart.js:19 Uncaught TypeError: {(intermediate value)(intermediate value)}[(0 , _transactions.getTokenFromAddress)(...)] is not a function
    　at getNormalizedTimestamp (balanceChart.js:19)
    　at Object.getChartDateFormat (balanceChart.js:128)
    　at BalanceGraph.render (balanceChart.js:16)
    　at finishClassComponent (react-dom.development.js:7873)
    　at updateClassComponent (react-dom.development.js:7850)
    　at beginWork (react-dom.development.js:8225)
    　at performUnitOfWork (react-dom.development.js:10224)
    　at workLoop (react-dom.development.js:10288)
    　at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    　at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
getNormalizedTimestamp @ balanceChart.js:19
getChartDateFormat @ balanceChart.js:128
render @ balanceChart.js:16
finishClassComponent @ react-dom.development.js:7873
updateClassComponent @ react-dom.development.js:7850
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
react-dom.development.js:9747 The above error occurred in the <BalanceGraph> component:
    　in BalanceGraph (created by I18n)
    　in I18n (created by Translate(BalanceGraph))
    　in Translate(BalanceGraph) (created by WalletTab)
    　in div (created by WalletTab)
    　in div (created by WalletTab)
    　in WalletTab (created by WalletTransactionsV2)
    　in TabsContainer (created by WalletTransactionsV2)
    　in WalletTransactionsV2 (created by I18n)
    　in I18n (created by Translate(WalletTransactionsV2))
    　in Translate(WalletTransactionsV2) (created by Connect(Translate(WalletTransactionsV2)))
    　in Connect(Translate(WalletTransactionsV2)) (created by Route)
    　in Route (created by withRouter(Connect(Translate(WalletTransactionsV2))))
    　in withRouter(Connect(Translate(WalletTransactionsV2))) (created by TransactionsDashboard)
    　in div (created by TransactionsDashboard)
    　in div (created by TransactionsDashboard)
    　in TransactionsDashboard (created by Connect(TransactionsDashboard))
    　in Connect(TransactionsDashboard) (created by Route)
    　in Route (created by withRouter(Connect(TransactionsDashboard)))
    　in withRouter(Connect(TransactionsDashboard)) (created by Route)
    　in Route (created by CustomRoute)
    　in ErrorBoundary (created by I18n)
    　in I18n (created by Translate(ErrorBoundary))
    　in Translate(ErrorBoundary) (created by CustomRoute)
    　in main (created by CustomRoute)
    　in CustomRoute (created by I18n)
    　in I18n (created by Translate(CustomRoute))
    　in Translate(CustomRoute) (created by Connect(Translate(CustomRoute)))
    　in Connect(Translate(CustomRoute)) (created by Route)
    　in Route (created by withRouter(Connect(Translate(CustomRoute))))
    　in withRouter(Connect(Translate(CustomRoute))) (created by App)
    　in Switch (created by App)
    　in div (created by App)
    　in section (created by App)
    　in main (created by App)
    　in section (created by OfflineWrapper)
    　in OfflineWrapper (created by Connect(OfflineWrapper))
    　in Connect(OfflineWrapper) (created by App)
    　in App (created by Route)
    　in Route (created by withRouter(App))
    　in withRouter(App)
    　in I18nextProvider
    　in Router (created by HashRouter)
    　in HashRouter
    　in Provider
React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:9747
captureError @ react-dom.development.js:10540
renderRoot @ react-dom.development.js:10391
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421

**Contents of parameter "tx" of getNormalizedTimestamp**
> amount: 6739858
confirmations: 18
data: ""
explorerLink: "https://www.blockchain.com/btctest/tx/eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4"
fee: 14598
id: "eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4"
recipientId: "mvcaQMDpXjYbjnkqdaVvkERpou7rTHVEwY"
senderId: "Unparsed Address"
timestamp: 1563621205000
type: 0

**BTC Transaction**
eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4
https://live.blockcypher.com/btc-testnet/tx/eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4/

### Actual result

An error occurs on the Bitcoin Wallet page

### Expected result

The Bitcoin Wallet page should be displayed

### Version

OS: Mac Mojave 10.14.5
Hub: 1.19.0

### Screenshot (if appropriate)

error

### PR DESCRIPTION
**Pull request by osvaldovega**
### What issue have I solved?

-- #2254 

### How have I implemented/fixed it?

There was no possible reproduce the issue, in the specific version and in the new ones, I found another errors related signIn process but not related to the BTC switcher in wallet.

After read the error message and check the component that throw that error I found that the possible cause could be fixed in previous PRs when the chart what improve.

What be able to fix was the problem related Sign In page with network switcher active and last active token was BTC, so when use is navigation into the app and switch the token to BTC and logout, this configuration was being use for Sign In again and was throwing some error message because of this, so I just update the Heade/SignIn component and the splashscreen and now is working properly.

### How has this been tested?

**case 1:**
1. Enable network switcher in settings.
2. In the Sign In page select Testnet and login.
3. In Dashboard switch the token to BTC.
4. Go to Wallet tab (NO ERROR at all).

**case 2**
1. Enable network switcher in settings.
2. In the Sign In page select Testnet and login.
3. Go to Wallet tab.
4. In Wallet switch the token to BTC (NO ERROR at all).
5. Switch back to LSK.
6. Switch back to BTC (NO ERRORs).
7. Logout
8. Log in
9. Go to Wallet (NO ERROR).

In all the tests that I made I tried with Testnet, Mainnet and Custom Node, I were not able to get the error the user describe.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by Efefefef** [comment]
Man, appreciate for your fix, but I cant accept it as a bugfix for this task.
I could not reproduce the exact error on the wallet page. 
But there is an error for sure with this segwit address mentioned by hitobb.
Just login as genesis and check the testnet transaction from 2MySvJQt3GGDB74isGg26jgsY2DofHQnQsq which is the address of https://coinfaucet.eu/en/btc-testnet/
The tx is shown as a outgoing instead of incoming
Trying to get tx details produce an error

**Comment by massao** [comment]
The problem seems to be on the normalize function: https://github.com/LiskHQ/lisk-hub/blob/7f5b5605d17b32dec8ab63004f66dfcb6643c7b5/src/utils/api/btc/transactions.js#L18-L59

the output value is being returned as `undefined`

**Comment by osvaldovega** [comment]
thx @Efefefef I review this with @massao and we be abled to found a solution for the problem, please check it again

**Comment by Efefefef** [comment]
@osvaldovega Check this out
https://jenkins.lisk.io/test/lisk-hub/PR-2368/#/explorer/accounts/2N3yZUXvGD2iMmRKGdVPppewtybcPhGc742
Unparsed address

https://jenkins.lisk.io/test/lisk-hub/PR-2368/#/explorer/transactions/5305099e8e5cb93bdb18257fa83988d70a7f11de107ae42411491d86b0cecf30
If I open this transaction details as a mkakDp2f31btaXdATtAogoqwXcdx1PqqFo
https://jenkins.lisk.io/test/lisk-hub/PR-2368/#/explorer/transactions/5305099e8e5cb93bdb18257fa83988d70a7f11de107ae42411491d86b0cecf30
I see the tx from 2Myf3fLXAJDXg8MBfX14vqrbdXWcrq56vrh to 2N53UATYsvmpAr9pauNM3tpbxTbToQfsP6i
Which is the other part of the transaction
https://tbtc.bitaps.com/5305099e8e5cb93bdb18257fa83988d70a7f11de107ae42411491d86b0cecf30
Faucets pay to many outputs, instead of creating single transactions - this saves on the fees
It looks like we did not consider this use case, I personally thought we get all the info from lisk service ready for use.
We still can parse the response I guess but i'm not sure if it's related to the original bug? Can you explain what was the problem you've fixed?

**Pull request merged**
