### PR TITLE
Show the usage tracking switcher in settings always - Closes #1454

### LINKED ISSUE #1454: Show the usage tracking switcher in settings always
Subtask of https://github.com/LiskHQ/lisk-hub/issues/1102

Show the switcher in settings always with a link to Privacy Policy.

Switcher title should say:
`Send anonymous usage statistics`

And have a subtitle:
`For more information refer to our [Privacy Policy](https://lisk.io/privacy)`

### PR DESCRIPTION
**Pull request by osvaldovega**
A new button is added in the settings page for the usage statistics, by default is disabled and only will be enable if the user change the settings, if not nothing will be track. 

### What issue have I solved?
-- #1454 

### How have I implemented/fixed it?

Just add one more toggle button in the settings page and update the reducer for be able to use this property at the time the user change it.

At this point this is only a change in the UI and settings reducer but not paired to Matomo (Piwik) yet.

Settings unit test updated

### How has this been tested?

At the moment only checking the UI and see that is aligned to the rest of buttons and that the toggle function works.

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by Efefefef** [comment]
Looks working to me
Nevertheless few things to fix:
🐛`anonymus` should be `anonymous`
🐛 something tries to set statistics local storage value to false (if true)

**Comment by osvaldovega** [comment]
@Efefefef thanks for the review I fixed the typo now, and the other problem that you mentioned I dont know why but as the code check first the local storage, something that you can do is clear the local storage and then check again, then you will see that is not happening any more.

This is related your last comment

**Comment by Efefefef** [comment]
👍

**Comment by osvaldovega** [comment]
@Efefefef I think you need to approve the PR so then I can merge it

**Pull request merged**
