### PR TITLE
Implement monitor header - Closes #2507

### LINKED ISSUE #2507: Implement the required visual changes to add monitoring screens
### Description
We'd like to add a link to header to directed to monitoring screens.

### Acceptance criteria
According to [designs](https://projects.invisionapp.com/d/main#/projects/prototypes/18539694):
- Add a button on the header to open the monitoring screens.
- From the inner tabs, transactions should be active by default.
- If users hover on a menu item, only the icon color changes to blue.
- If users navigate to a route, the corresponding menu item expands with a slight animation and shows its title. This expansion (and animation) is visible only in wide screens.

### PR DESCRIPTION
**Pull request by slaweet**
### What issue have I solved?

Closes #2507

### How have I implemented/fixed it?

- [x] Add "Monitor" to top bar
- [x] Update top bar to hide unactive menu item labels
- [x] Create Switcher toolbox component 
- [x] Create Switcher component demo
- [x] Create monitor header
- [x] Add "Monitor" icon assets

Note that I introduced one new dependency with MIT licence: https://github.com/jest-community/jest-watch-toggle-config/blob/master/LICENSE that I added not to waste time waiting for test coverage when writing tests but being able to quickly switch the coverage on.

### How has this been tested?

- Navigate main menu items
- Check Monitor header

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by Efefefef** [comment]
In order to test it #2524 should be merged first, cause Transaction monitor is not merged yet.

**Comment by slaweet** [comment]
> 🎨 The animation of top header item unfolding is laggy

The animation is laggy because of rendering time of our pages (e.g. see https://github.com/LiskHQ/lisk-hub/issues/2482). Improving the rendering time is IMO a separate issue. Should I disable the animation until the performance issues are resolved @reyraa?

**Comment by slaweet** [comment]
@Efefefef I just pushed an optimization proposed by Ali, please check again.

**Comment by Efefefef** [comment]
Still looks laggy guys even on top macbook pro. What should we do?

**Comment by slaweet** [comment]
> Still looks laggy guys even on top macbook pro. What should we do?

@reyraa ?

**Comment by reyraa** [comment]
Remove the transition if it don't work. We can introduce it later.

**Pull request merged**
