### PR TITLE
Minimal extension system - Closes #1710 #1709 #1740

### LINKED ISSUE #1710: Implement the window.LiskHubExtensions module
This is a subtask of #1706 epic.

Implement the window.LiskHubExtensions module with:
- LiskHubExtensions.addModule({ identifier, reactComponent });
Stores identifier and reactComponent in ‘extensions’ redux store
- LiskHubExtensions.addPage({ path, reactComponent });
- LiskHubExtensions.Components = { Button, Input, Box, ....};

As outlined in 
https://github.com/LiskHQ/lisk-hub/blob/8080aef35d577a2f74a8a7d8714cebfefed4da2e/src/utils/liskHubExtensions.js#L6-L32

### PR DESCRIPTION
**Pull request by michaeltomasik**
### What issue have I solved?

#1710 #1709 #1740

### How has this been tested?

Go to http://localhost:8080/#/extensions
Add one of:
https://codepen.io/michaeltomasik/pen/JxweXa.js
https://codepen.io/michaeltomasik/pen/rPoXGE.js

https://codepen.io/michaeltomasik/pen/jdXgBp.js <--- Not compiled component

It should add modules to a dashboard ONLY if you are on a development env

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by Efefefef** [comment]
I think its already much better this way:
Trusted marketplace to use
Extension source validation to prevent adding fraud extension

I think we need to describe the rules for both users and creators on the extension page

**Comment by Efefefef** [comment]
But still, I would like to point out I think that using`eval` to execute scripts is a very bad idea and hope it will be used only for the sake of testing the extensions idea.

**Comment by Efefefef** [comment]
@slaweet Can you update the specification? I am not aware of what I should test

**Comment by slaweet** [comment]
@Efefefef I've added the last point to https://github.com/LiskHQ/lisk-hub/issues/1709 .
I have the feeling it isn't much detailed, but I can't think of what else is missing?

**Comment by Efefefef** [comment]
@slaweet What exactly should be disabled in the production mode?

**Comment by slaweet** [comment]
@Efefefef I've put more details to https://github.com/LiskHQ/lisk-hub/issues/1709 to answer your question. 
@michaeltomasik, please implement the extra message and disabled button mentioned there.

**Pull request merged**
