### PR TITLE
Align design of transactions details - Closes #2171

### LINKED ISSUE #2171: Align the design of Transaction details
Invision:
https://projects.invisionapp.com/d/main#/console/17570736/368363502/preview

Fonts, icons, copy icon, header, popups, everything…

Design
image

App
image

### PR DESCRIPTION
**Pull request by slaweet**
### What issue have I solved?

#2171

### How have I implemented/fixed it?

- [x] Change style of Sender and Recipient
- [x] Change style of all labels and values
- [x] Change header of all transaction types to be below the box header and contain transaction type icons
- [x] Reorder amount and fee
- [x] Implement tooltip for "Confirmations"

### How has this been tested?

Visit the transaction detail page for:
- transfer (LSK http://localhost:8080/#/explorer/transactions/12400920197376315040 and BTC http://localhost:8080/#/explorer/transactions/553787aa91a55e0385beb81a0a549f02cb3be8492b452fe8b09c1729165a8362)
- vote http://localhost:8080/#/explorer/transactions/9400328732388578360
- 2nd passphrase registration http://localhost:8080/#/explorer/transactions/16730031459010386209
- delegate registration http://localhost:8080/#/explorer/transactions/2697129531259680873

Transaction ids used from
https://github.com/LiskHQ/lisk-hub/blob/5fee32e44333ec62f7bbc049b8f54ff5587c19f9/test/cypress/e2e/txDetails.spec.js#L7-L10
### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by reyraa** [comment]
The copy of the confirmation tooltip:
> Confirmations refer to the number of blocks added to the Lisk blockchain after a transaction has been submitted. The more confirmations registered, the more secure the transaction becomes.

**Comment by slaweet** [comment]
> 🐛 Copy link button: padding should be >, space between label and icon should be >

Button padding is according ot the [style guide](https://projects.invisionapp.com/d/main#/console/17866402/370534614/inspect) - should be fixed in design @imdominic 

> 🐛 All tx: Last row padding-bottom should be >

Fixed

> 🐛 All tx: Confirmations should have more space from the vertical divider(and Amount in transfer)

Fixed

> 🐛 All tx: Date in design in 12hr format

Fixed

> 🐛 BTC tx details: LSK fee and amount. LSK specific tooltip

Fixed

> 🐛 Vote: There should be no divider between Added and Removed

There should be a divider https://projects.invisionapp.com/d/main#/console/17570736/368355793/inspect and it wasn't. Fixed

> 🐛 Delegate Registration: Account instead of Account nickname

Fixed

> 🐛 Vote: Date is not on the right place
> 🐛 LSK tx details: message should be the last column

Order of the transaction-specific data in the design doesn't make sense to me. I forgot to raise this point before. Message is specific for send, Votes are specific for vote transaction. IMO these two should be in the same place. Right now they are implemented to be between account and date. Can we have it like this @reyraa @imdominic?

**Comment by slaweet** [comment]
BTC in amount and fee  fixed

**Comment by Efefefef** [comment]
I approve. But the question above about the order is open :)
Do we already have a pipeline to request PO decision? @sridharmeganathan

**Comment by slaweet** [comment]
Talked to Ali and we agreed on this order of data for Transfer
```
| Sender    	|               	|
|-----------	|---------------	|
| Recipient 	|               	|
|-----------	|---------------	|
| Date      	| Confirmations 	|
|-----------	|---------------	|
| Amount    	| Fee           	|
|-----------	|---------------	|
| Message   	|               	|
```

And this for vote
```
| Type          	|               	|
|---------------	|---------------	|
| Voter         	|               	|
|---------------	|---------------	|
| Date          	| Confirmations 	|
|---------------	|---------------	|
| Fee           	|               	|
|---------------	|---------------	|
| Added votes   	|               	|
|---------------	|---------------	|
| Removed votes 	|               	|
```

Ali promised to talk to @imdominic to update designs

**Comment by slaweet** [comment]
@massao I think the bug you found is not related to this PR, but I fixed it anyway: https://github.com/LiskHQ/lisk-hub/pull/2235/commits/5af2398f8c40449d3fff2eeae5a90886a97ea546

**Pull request merged**
