### PR TITLE
Rerun failed e2e tests with recording - #1940

### PR DESCRIPTION
**Pull request by Efefefef**
### What issue have I solved?

#1940 

### How have I implemented/fixed it?

setup new project id 

### Review checklist
- The PR follows our [Test guide](/LiskHQ/lisk-hub/blob/development/docs/TEST_GUIDE.md)
- The PR follows our [CSS guide](/LiskHQ/lisk-hub/blob/development/docs/CSS_GUIDE.md)

### CODE REVIEW

**Comment by Efefefef** [comment]
@fchavant Doesn't work. Please check this run with a failed test. 
https://jenkins.lisk.io/blue/organizations/jenkins/lisk-hub/detail/PR-1941/6/pipeline

**Comment by fchavant** [comment]
@Efefefef the Jenkins build you linked ran before 9am while my last commit in this PR was around 1pm.

**Comment by Efefefef** [comment]
@fchavant We must include the relative path to the test files for example
`cypress run --project test/cypress "--record" "--spec" "test/cypress/e2e/send.spec.js"`
https://ci.lisk.io/blue/organizations/jenkins/lisk-hub/detail/PR-1941/13/pipeline

**Comment by fchavant** [comment]
@Efefefef how can I find out what the path of the spec file is? Can I assume it'll always be `test/cypress/e2e/`?

**Comment by Efefefef** [comment]
@fchavant Yes

**Comment by fchavant** [comment]
@Efefefef done in https://github.com/LiskHQ/lisk-hub/pull/1941/commits/77d69705d3e9c3e01234c85f72e35c9fc900c772

**Comment by Efefefef** [comment]
👍 It Works

**Pull request merged**
